# Generated by Django 3.1.5 on 2021-09-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegModel',
            new_name='CustomerRegModel',
        ),
    ]
