# Generated by Django 3.1.5 on 2021-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210915_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpoyeeRegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=10)),
                ('working_category', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
