# Generated by Django 3.1.5 on 2021-09-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_empoyeeregmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpoyeeRegModel',
            new_name='EmployeeRegModel',
        ),
    ]
