# Generated by Django 3.1.5 on 2021-09-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pendingappointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingAppointment',
            new_name='Appointment',
        ),
    ]
